package data

import scala.xml.pull._
import scala.io.Source
import java.io.File
import com.mongodb.casbah.commons.{ MongoDBObject, MongoDBList, MongoDBListBuilder }
import com.mongodb.casbah.commons.Imports.DBObject

object Importer {
  def apply(db: String, filename: String) {
    val src = Source.fromFile(new File(filename))
    val er = new XMLEventReader(src)

    val mongoDb = DataManager.getConn(db)
    var numRecordsProcessed = 0;

    var current = MongoDBObject.newBuilder
    var tags = new MongoDBListBuilder
    var otherColl = new MongoDBListBuilder

    while (er.hasNext) {
      val e = er.next
      e match {
        case comment: EvComment => println(comment.text)
        case elem: EvElemStart => {
          val attrs = elem.attrs.asAttrMap
          if (elem.label == "node" || elem.label == "way" || elem.label == "relation") {
            current = MongoDBObject.newBuilder
            current += ("osmid" -> attrs("id").toInt)
          }
          elem.label match {
            case "node" => current += ("loc" -> MongoDBList(attrs("lon").toFloat, attrs("lat").toFloat))
            case "tag" => tags += MongoDBObject("k" -> attrs("k"), "v" -> attrs("v"))
            case "nd" => otherColl += attrs("ref").toInt
            case "member" => otherColl += MongoDBObject("type" -> attrs("type"), "ref" -> attrs("ref").toInt)

            case "osm" => println("Processing OSM v" + attrs("version") + " generated by " + attrs("generator") + ".")
            case "bound" => println("Importing bounds box: " + attrs("box") + ".")

            case _ =>
          }
        }
        case elem: EvElemEnd => {
          var shouldPersist = false
          elem.label match {
            case "node" => {
              shouldPersist = true
            }
            case "way" => {
              current += "nodes" -> otherColl.result
              otherColl = new MongoDBListBuilder
              shouldPersist = true
            }
            case "relation" => {
              current += "members" -> otherColl.result
              otherColl = new MongoDBListBuilder
              shouldPersist = true
            }
            case "osm" => println("Finished processing " + numRecordsProcessed + " records.")
            case _ =>
          }
          if (shouldPersist) {
            numRecordsProcessed += 1
            current += "tags" -> tags.result
            tags = new MongoDBListBuilder
            mongoDb(elem.label).insert(current.result)
          }
        }
        case _ =>
      }
    }
  }
}